name: Fix Hyperlinks
on:
  workflow_dispatch:  # Manual trigger only
  
jobs:
  fix-links:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This fixes the permission error
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Fix hyperlink naming conventions
      run: |
        # Fix references.md
        sed -i 's|game_overview\.md|game-overview.md|g' references.md
        sed -i 's|three_tier_system\.md|three-tier-system.md|g' references.md
        
        # Fix hellionaires-index.md
        sed -i 's|gameplay\.md|gameplay-mechanics.md|g' hellionaires-index.md
        
        # Fix docs-readme.md directory structure
        sed -i 's|universe-bible/||g' docs-readme.md
        sed -i 's|technical-systems/||g' docs-readme.md
        sed -i 's|game-development/||g' docs-readme.md
        sed -i 's|narrative-content/||g' docs-readme.md
        sed -i 's|development-process/||g' docs-readme.md
        
        # Fix ALL markdown files for common underscore patterns
        find . -name "*.md" -type f -exec sed -i 's|consciousness_cycles\.md|consciousness-cycles.md|g' {} \;
        find . -name "*.md" -type f -exec sed -i 's|game_overview\.md|game-overview.md|g' {} \;
        find . -name "*.md" -type f -exec sed -i 's|three_tier_system\.md|three-tier-system.md|g' {} \;
        find . -name "*.md" -type f -exec sed -i 's|kill_switch_protocol\.md|kill-switch-protocol.md|g' {} \;
        find . -name "*.md" -type f -exec sed -i 's|museum_framework\.md|museum-framework.md|g' {} \;
        find . -name "*.md" -type f -exec sed -i 's|fps_tableaux\.md|fps-tableaux.md|g' {} \;
        find . -name "*.md" -type f -exec sed -i 's|artifact_interaction\.md|artifact-interaction.md|g' {} \;
        find . -name "*.md" -type f -exec sed -i 's|ripple_effects\.md|ripple-effects.md|g' {} \;
        find . -name "*.md" -type f -exec sed -i 's|palmer_eldritch\.md|palmer-eldritch.md|g' {} \;
        find . -name "*.md" -type f -exec sed -i 's|spparks_system\.md|spparks-system.md|g' {} \;
        find . -name "*.md" -type f -exec sed -i 's|singularity_room\.md|singularity-room.md|g' {} \;
        
        # Also fix any remaining gameplay references
        find . -name "*.md" -type f -exec sed -i 's|]\(gameplay\.md\)|](gameplay-mechanics.md)|g' {} \;
        
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --staged --quiet || git commit -m "🔧 Fix hyperlink naming conventions automatically"
        git push
